replicaCount: 1

image:
  repository: drshooby/service2
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8081

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10
